apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ws
spec:
  containers:
    - name: gophr-ws
      image: gophr-ws:staging
      ports:
        - containerPort: 80
        - containerPort: 443
