apiVersion: v1
kind: Service
metadata:
  name: gophr-ws-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 32080
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      nodePort: 32443
      targetPort: 443
      protocol: TCP
  selector:
    component: ws
