apiVersion: v1
kind: ReplicationController
metadata:
  name: api-rc
  labels:
    module: api
  namespace: gophr
spec:
  replicas: 1
  selector:
    module: api
  template:
    metadata:
      labels:
        module: api
      namespace: gophr
    spec:
      containers:
      - name: api
        image: gophr-api-dev:v1
        ports:
        - containerPort: 3000
