apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    module: api
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 30100
  selector:
    module: api
