apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dd-agent
  labels:
    module: dd-agent
  namespace: gophr
spec:
  template:
    metadata:
      labels:
        module: dd-agent
      name: dd-agent
    spec:
      containers:
      - image: gophr-dd-agent-dev:v1
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
        env:
          - name: API_KEY
            value: "{{DATADOG_API_KEY}}"
          - name: KUBERNETES
            value: "yes"
          - name: SD_BACKEND
            value: docker
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: secrets
            mountPath: /secrets
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - name: secrets
          secret:
            secretName: gophr-secrets
