apiVersion: v1
kind: Service
metadata:
  name: dd-agent-svc
  labels:
    module: dd-agent
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: http
      protocol: UDP
      port: 8125
      nodePort: 30111
  selector:
    module: dd-agent
