apiVersion: v1
kind: Service
metadata:
  name: router-svc
  labels:
    module: router
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 30200
  selector:
    module: router
