apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depot-vol-pvc
  labels:
    module: depot-vol
  namespace: gophr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600G
