apiVersion: v1
kind: ReplicationController
metadata:
  name: depot-vol-rc
  labels:
    module: depot-vol
  namespace: gophr
spec:
  replicas: 1
  selector:
    module: depot-vol
  template:
    metadata:
      labels:
        module: depot-vol
      namespace: gophr
    spec:
      containers:
        - name: depot-vol
          image: gophr-depot-vol-dev:v1
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /repos
              name: repos
      volumes:
        - name: repos
          emptyDir:
            medium: ""
