apiVersion: v1
kind: ReplicationController
metadata:
  name: depot-vol-rc
  labels:
    module: depot-vol
  namespace: gophr
spec:
  replicas: 1
  selector:
    module: depot-vol
  template:
    metadata:
      labels:
        module: depot-vol
      namespace: gophr
    spec:
      containers:
        - name: depot-vol
          image: gcr.io/valid-song-142700/gophr-depot-vol:1.0.0
          ports:
            - name: nfs
              containerPort: 2049
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /repos
              name: repos
      volumes:
        - name: repos
          gcePersistentDisk:
            pdName: gophr-volume-depot
            fsType: ext4
            readOnly: false
