apiVersion: v1
kind: Service
metadata:
  name: depot-vol-svc
  labels:
    module: depot-vol
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: nfs
      port: 2049
      nodePort: 30980
    - name: rpcbind
      port: 111
      nodePort: 30981
  selector:
    module: depot-vol
