apiVersion: v1
kind: Service
metadata:
  name: depot-vol-svc
  labels:
    module: depot-vol
  namespace: gophr
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    module: depot-vol
