apiVersion: v1
kind: PersistentVolume
metadata:
  name: depot-vol-pv
	labels:
    module: depot-vol
  namespace: gophr
spec:
  capacity:
		storage: 600G
  accessModes:
    - ReadWriteMany
  nfs:
    server: "depot-vol-svc"
    path: "/repos"
