apiVersion: v1
kind: PersistentVolume
metadata:
  name: depot-vol-pv
	labels:
    module: depot-vol
  namespace: gophr
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/depot
