language: go

sudo: required

before_install:
  - go get -d github.com/libgit2/git2go
  - $GOPATH/src/github.com/libgit2/git2go/script/install-libgit2.sh

go:
  - 1.6
  - 1.7

notifications:
  - email: false
