FROM golang:alpine

# Install git for dependencies
RUN set -ex && apk add --update 'git' && apk add 'bash'

# Build source and move things around.
COPY . /go/src/github.com/skeswa/gophr
RUN cd /go/src/github.com/skeswa/gophr/migrator \
    && go get -d -v \
    && go build -o migrator \
    && chmod +x ./migrator \
    && mkdir /gophr \
    && mv ./migrator /gophr/migrator \
    && mv ../common/db/migrations /gophr/migrations \
    && mv ../infra/scripts/wait-for-it.sh /gophr/wait-for-it.sh \
    && cd /gophr \
    && rm -rf /go/src/github.com/skeswa/gophr

# Uninstall unnecessary tools.
RUN set -ex && apk del git

# Set the environment variables
ENV GOPHR_DB_ADDR="db"
ENV GOPHR_MIGRATIONS_PATH="/gophr/migrations"

# Run the migrator.
WORKDIR /gophr
CMD ./wait-for-it.sh -h db -p 9042 -t 0 -- ./migrator
