#! /bin/bash

scripts_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
infra_dir="$( cd "$( dirname "$scripts_dir" )" && pwd )"
project_dir="$( cd "$( dirname "$infra_dir" )" && pwd )"

# Color variables
esc_seq="\x1b["
no_color=$esc_seq"39;49;00m"
green_color=$esc_seq"32;01m"

# Kill children on exit
trap 'lsof -i tcp:1337 | awk '"'"'NR!=1 {print $2}'"'"' | xargs kill' SIGINT SIGTERM

echo "Link gophr dev cluster..."
docker-machine ssh gophr -N -L 1337:localhost:8080 &
echo -e "${green_color}✓ Gophr dev cluster control port exposed on localhost:1337!${no_color}"

echo "Creating file system link with gophr dev cluster..."
echo -e "${green_color}✓ Created file system link with gophr dev cluster successfully!${no_color}"
docker-rsync -verbose -src="$project_dir" -dst="/opt/gophr" gophr

# Wait until each background process is killed
wait
