#! /bin/bash

# Get base directories
scripts_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
infra_dir="$( dirname $scripts_dir )"
images_dir="$infra_dir/images"

# Color variables
esc_seq="\x1b["
no_color=$esc_seq"39;49;00m"
green_color=$esc_seq"32;01m"

echo "Creating gophr dev docker images..."

# Bind docker to the gophr docker machine
eval $(docker-machine env gophr)

docker build --rm -t 'gophr-fe-api:dev' "$images_dir/fe-api-dev"
docker build --rm -t 'gophr-web-server:dev' "$images_dir/web-server-dev"
echo -e "${green_color}✓ Gophr docker images created successfully!${no_color}"
