apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    module: web
  namespace: gophr
spec:
  replicas: 1
  selector:
    module: web
  template:
    metadata:
      labels:
        module: web
      namespace: gophr
    spec:
      containers:
      - name: web
        image: gcr.io/valid-song-142700/gophr-web:1.0.0
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /secrets
          name: secrets
      volumes:
      - name: secrets
        secret:
          secretName: gophr-secrets
