apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    module: web
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30480
    - name: https
      port: 443
      nodePort: 30443
  selector:
    module: web
