apiVersion: v1
kind: Service
metadata:
  name: fe-api-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 31080
      targetPort: 3000
      protocol: TCP
  selector:
    tier: fe
    role: api
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: fe-api-dev-rc
spec:
  template:
    metadata:
      labels:
        tier: fe
        role: api
        env: dev
    spec:
      containers:
        - name: fe-api-dev
          image: gophr-fe-api:dev
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
