apiVersion: v1
kind: ReplicationController
metadata:
  name: depot-ext-rc
  labels:
    module: depot-ext
  namespace: gophr
spec:
  replicas: 1
  selector:
    module: depot-ext
  template:
    metadata:
      labels:
        module: depot-ext
      namespace: gophr
    spec:
      containers:
      - name: depot-ext
        image: gcr.io/valid-song-142700/gophr-depot-ext:1.0.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /secrets
          name: secrets
        - mountPath: /repos
          name: repos
      volumes:
      - name: repos
        gcePersistentDisk:
          pdName: gophr-volume-depot
          fsType: ext4
      - name: secrets
        secret:
          secretName: gophr-secrets
