apiVersion: v1
kind: PersistentVolume
metadata:
  name: depot-ext-vol
spec:
  capacity:
    storage: 600G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: gophr-volume-depot
    fsType: ext4
