apiVersion: v1
kind: ReplicationController
metadata:
  name: scheduler-worker-rc
  labels:
    module: scheduler-worker
  namespace: gophr
spec:
  replicas: 2
  selector:
    module: scheduler-worker
  template:
    metadata:
      labels:
        module: scheduler-worker
      namespace: gophr
    spec:
      containers:
      - name: scheduler-worker
        image: "gcr.io/{{GCE_PROJECT_ID}}/gophr-scheduler-worker:1.0.2"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /secrets
          name: secrets
      volumes:
      - name: secrets
        secret:
          secretName: gophr-secrets
