apiVersion: v1
kind: Service
metadata:
  name: scheduler-worker-svc
  labels:
    module: scheduler-worker
  namespace: gophr
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    module: scheduler-worker
