apiVersion: v1
kind: ReplicationController
metadata:
  name: depot-int-rc
  labels:
    module: depot-int
  namespace: gophr
spec:
  replicas: 1
  selector:
    module: depot-int
  template:
    metadata:
      labels:
        module: depot-int
      namespace: gophr
    spec:
      containers:
      - name: depot-int
        image: "gcr.io/{{GCE_PROJECT_ID}}/gophr-depot-int:1.1.3"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /repos
          name: repos
      volumes:
      - name: repos
        persistentVolumeClaim:
          claimName: depot-vol-pvc
          readOnly: false
