apiVersion: v1
kind: Service
metadata:
  name: depot-int-svc
  labels:
    module: depot-int
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30960
  selector:
    module: depot-int
