apiVersion: v1
kind: Pod
metadata:
  name: migrator
  namespace: gophr
  labels:
    module: migrator
spec:
  containers:
  - name: api
    image: "gcr.io/{{GCE_PROJECT_ID}}/gophr-migrator:1.1.0"
  restartPolicy: Never
