apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gophr-db-ds
  labels:
    component: db
spec:
  template:
    metadata:
      labels:
        component: db
    spec:
      containers:
        - env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gophr-db:latest
          name: gophr-db
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          resources:
            request:
              cpu: 0.1
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
