#! /bin/bash

# Color variables
esc_seq="\x1b["
no_color=$esc_seq"39;49;00m"
green_color=$esc_seq"32;01m"

echo "Exposing gophr dev cluster..."
echo -e "${green_color}✓ Gophr dev cluster control port exposed on localhost:1337!${no_color}"
docker-machine ssh gophr -N -L 1337:localhost:8080
