#! /bin/bash

# Get base directories
scripts_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
project_dir="$( dirname $scripts_dir )"

# Color variables
no_color="\033[0m"
green_color="\033[0;32m"

echo "Creating gophr dev docker images..."
&& docker build --rm -t 'gophr-frontend-api:dev' "$project_dir/frontend/images/api-dev" &> /dev/null \
&& docker build --rm -t 'gophr-frontend-web:dev' "$project_dir/frontend/images/web-dev" &> /dev/null \
&& docker build --rm -t 'gophr-frontend-search:dev' "$project_dir/frontend/images/search-dev" &> /dev/null \
&& docker build --rm -t 'gophr-db:dev' "$project_dir/common/images/db-dev" &> /dev/null \
&& echo "${green_color}✓ Gophr docker images created successfully${no_color}"
