#! /bin/bash

NEW_LINE_CHAR="
"

# Color variables
esc_seq="\x1b["
no_color=$esc_seq"39;49;00m"
green_color=$esc_seq"32;01m"

echo "Updating gophr cluster host..."

# Bind docker to the gophr docker machine
eval $(docker-machine env gophr)

# Patch the hosts file
local_host_alias="gophr.dev"
hosts_file_path="/etc/hosts"
docker_machine_ip=$(docker-machine ip gophr)
gophr_dev_host=$(sudo grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\s+${local_host_alias}$" --color=never ${hosts_file_path})

if [[ -z "$gophr_dev_host" ]]; then
  # This means that there is gophr dev host yet, so we must append it
  echo "${NEW_LINE_CHAR}${docker_machine_ip} ${local_host_alias}" | sudo tee -a $hosts_file_path
else
  # This means that there is a gophr dev host, so we must replace it
  sudo sed -E -e "s/${gophr_dev_host}/${docker_machine_ip} ${local_host_alias}/" -i "" $hosts_file_path
fi

echo -e "${green_color}✓ Gophr cluster host updated successfully!${no_color}"
