apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc-a
  labels:
    module: db
    ordinal: a
  namespace: gophr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        module: db
        ordinal: a
    spec:
      containers:
        - resources:
            requests:
              memory: 600M
            limits:
              cpu: 0.5
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: gophr-db-dev:v1
          name: db
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
      volumes:
        - name: cassandra-data
          emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc-b
  labels:
    module: db
    ordinal: b
  namespace: gophr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        module: db
        ordinal: b
    spec:
      containers:
        - resources:
            requests:
              memory: 600M
            limits:
              cpu: 0.5
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: gophr-db-dev:v1
          name: db
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
      volumes:
        - name: cassandra-data
          emptyDir: {}
