apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc-a
  labels:
    module: db
    ordinal: a
  namespace: gophr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        module: db
        ordinal: a
    spec:
      nodeSelector:
        ordinal: '1'
      containers:
        - resources:
            requests:
              memory: 2G
            limits:
              cpu: 1
          env:
            - name: MAX_HEAP_SIZE
              value: 1536M
            - name: HEAP_NEWSIZE
              value: 512M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "gcr.io/{{GCE_PROJECT_ID}}/gophr-db:1.4.0"
          name: db
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
            - mountPath: /secrets
              name: secrets
      volumes:
        - name: cassandra-data
          gcePersistentDisk:
            pdName: gophr-volume-db-a
            fsType: ext4
        - name: secrets
          secret:
            secretName: gophr-secrets
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc-b
  labels:
    module: db
    ordinal: b
  namespace: gophr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        module: db
        ordinal: b
    spec:
      nodeSelector:
        ordinal: '2'
      containers:
        - resources:
            requests:
              memory: 2G
            limits:
              cpu: 1
          env:
            - name: MAX_HEAP_SIZE
              value: 1536M
            - name: HEAP_NEWSIZE
              value: 512M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "gcr.io/{{GCE_PROJECT_ID}}/gophr-db:1.4.0"
          name: db
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
            - mountPath: /secrets
              name: secrets
      volumes:
        - name: cassandra-data
          gcePersistentDisk:
            pdName: gophr-volume-db-b
            fsType: ext4
        - name: secrets
          secret:
            secretName: gophr-secrets
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db-rc-c
  labels:
    module: db
    ordinal: c
  namespace: gophr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        module: db
        ordinal: c
    spec:
      nodeSelector:
        ordinal: '3'
      containers:
        - resources:
            requests:
              memory: 2G
            limits:
              cpu: 1
          env:
            - name: MAX_HEAP_SIZE
              value: 1536M
            - name: HEAP_NEWSIZE
              value: 512M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "gcr.io/{{GCE_PROJECT_ID}}/gophr-db:1.4.0"
          name: db
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
            - mountPath: /secrets
              name: secrets
      volumes:
        - name: cassandra-data
          gcePersistentDisk:
            pdName: gophr-volume-db-c
            fsType: ext4
        - name: secrets
          secret:
            secretName: gophr-secrets
