apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: db-ds
  labels:
    module: db
  namespace: gophr
spec:
  template:
    metadata:
      labels:
        module: db
      namespace: gophr
    spec:
      containers:
        - command:
            - /run.sh
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: gcr.io/valid-song-142700/gophr-db:1.0.0
          name: db
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          resources:
            requests:
              cpu: 0.5
          volumeMounts:
            - mountPath: /cassandra_data
              name: cassandra-data
  # These are converted to volume claims by the daemon set and mounted at the
  # paths mentioned above.  Storage can be automatically created for the pods
  # depending on the cloud environment.
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
