apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: db-ps
  labels:
    module: db
  namespace: gophr
spec:
  serviceName: db-svc
  replicas: 3
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        module: db
      namespace: gophr
    spec:
      containers:
      - name: db
        image: gcr.io/valid-song-142700/gophr-db:1.1.0
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        env:
          - name: MAX_HEAP_SIZE
            value: 1024M
          - name: HEAP_NEWSIZE
            value: 256M
          - name: CASSANDRA_SEEDS
            value: "db-ps-0.db-svc.gophr.svc.cluster.local,db-ps-1.db-svc.gophr.svc.cluster.local,db-ps-2.db-svc.gophr.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "gophr-cassandra-cluster"
          - name: CASSANDRA_RING_DELAY
            value: "6000"
          - name: CASSANDRA_DC
            value: "DC1-Data"
          - name: CASSANDRA_RACK
            value: "gophr-cassandra-cluster_Rack1"
          - name: CASSANDRA_OPEN_JMX
            value: "true"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        # - name: CASSANDRA_GC_STDOUT
        #  value: "true"
        volumeMounts:
        # These volume mounts are persistent. They're like inline claims,
        # but not exactly because the names need to match exactly one of
        # the pet volumes.
        - name: cassandra-data
          mountPath: /cassandra_data
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
  volumeClaimTemplates:
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  - metadata:
      name: cassandra-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 115Gi
