apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    module: db
  namespace: gophr
spec:
  ports:
    - name: cql
      port: 9042
    - name: jmx
      port: 7199
  selector:
    module: db
