apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    module: db
  namespace: gophr
spec:
  type: NodePort
  ports:
    - name: cql
      port: 9042
      nodePort: 30942
  selector:
    module: db
