export const GET_PACKAGE = 'GET_PACKAGE';
export const GET_PACKAGE_REQUEST = 'GET_PACKAGE_REQUEST';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const GET_PACKAGE_FAILURE = 'GET_PACKAGE_FAILURE';

export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_PACKAGES_REQUEST = 'GET_PACKAGES_REQUEST';
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
export const GET_PACKAGES_FAILURE = 'GET_PACKAGES_FAILURE';

export const REGISTER = 'REGISTER';
export const AUTHENTICATION_REQUEST = 'REGISTER_REQUEST';
export const AUTHENTICATION_SUCCESS = 'REGISTER_SUCCESS';
export const AUTHENTICATION_FAILURE = 'REGISTER_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAILURE = 'SET_PASSWORD_FAILURE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const GET_SUBCRIPTIONS = 'GET_SUBCRIPTIONS'
export const GET_SUBCRIPTIONS_REQUEST = 'GET_SUBCRIPTIONS_REQUEST';
export const GET_SUBCRIPTIONS_SUCCESS = 'GET_SUBCRIPTIONS_SUCCESS';
export const GET_SUBCRIPTIONS_FAILURE = 'GET_SUBCRIPTIONS_FAILURE';

export const GET_TOKENS = 'GET_TOKENS';
export const GET_TOKENS_REQUEST = 'GET_TOKENS_REQUEST';
export const GET_TOKENS_SUCCESS = 'GET_TOKENS_SUCCESS';
export const GET_TOKENS_FAILURE = 'GET_TOKENS_FAILURE';

export function requestGoPackage{
  return {
    type: REQUEST_GO_PACKAGES,
  };
}

export function selectGoPackage{
  return {
    type: SELECT_GO_PACKAGE,
  };
}
