apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    role: api
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api-rc
spec:
  template:
    spec:
      containers:
        - name: fe-api-dev
          image: gophr-fe-api:dev
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
